use BAZAAR_TECH


-- Total Number of Orders
SELECT COUNT(DISTINCT(order_number)) AS TOTAL_ORDERS
FROM DATASET_2

--Total Sales Revenue
SELECT (amount_per_unit*ordered_quantity)-(item_discount) AS ITEM_REVENUE
FROM DATASET_2

SELECT ROUND(SUM(ITEM_REVENUE), 0) AS TOTAL_REVENUE
FROM (SELECT (amount_per_unit*ordered_quantity)-(item_discount) AS ITEM_REVENUE
FROM DATASET_2) AS B

-- AVERAGE Order Value
SELECT SUM(ITEM_REVENUE) AS ORDER_REVENUE
FROM (SELECT order_number, (amount_per_unit*ordered_quantity)-(item_discount) AS ITEM_REVENUE
FROM DATASET_2) AS B
GROUP BY order_number


SELECT ROUND(AVG(ORDER_REVENUE),0) AS AVG_ORDER_VALUE
FROM (SELECT SUM(ITEM_REVENUE) AS ORDER_REVENUE
FROM (SELECT order_number, (amount_per_unit*ordered_quantity)-(item_discount) AS ITEM_REVENUE
FROM DATASET_2) AS B
GROUP BY order_number) AS C

-- Distribution of orders by warehouse and store

SELECT order_warehouse_id, store_id, COUNT(DISTINCT(order_number)) AS NO_OF_ORDERS
FROM DATASET_2
GROUP BY order_warehouse_id, store_id
ORDER BY NO_OF_ORDERS DESC

-- Top 5 selling itemsSELECT TOP 5 item_name, item_id, COUNT(item_name) AS TOP_SELLING_ITEMS_COUNT
FROM DATASET_2
GROUP BY item_name, item_id
ORDER BY COUNT(item_name) DESC

-- How many users signed up through paid channels?
SELECT acquisition_platform, COUNT(DISTINCT(store_id)) as NO_OF_USERS
FROM DATASET_1
WHERE acquisition_platform != 'Organic' 
GROUP BY acquisition_platform
ORDER BY NO_OF_USERS DESC


-- What % of users placed at least one order?SELECT COUNT(FIRST_ORDER_DATE) AS NO_OF_USERS,COUNT(store_id) AS TOTALFROM DATASET_1 SELECT ROUND(CAST(NO_OF_USERS AS FLOAT)/TOTAL*100, 2) AS USER_PERCENTFROM (SELECT COUNT(first_order_date) AS NO_OF_USERS,COUNT(store_id) AS TOTALFROM DATASET_1) AS A-- From which channel are most of the users acquired?SELECT TOP 1 acquisition_platform, COUNT(DISTINCT(store_id)) as NO_OF_USERS
FROM DATASET_1
GROUP BY acquisition_platform
ORDER BY NO_OF_USERS DESC
-- What % of orders were canceled?SELECT 
    ROUND(
	(COUNT(DISTINCT CASE WHEN order_status = 'CANCELLED' THEN order_number END) * 100.0) / 
    COUNT(DISTINCT order_number), 2) AS CANCELLED_PERCENTAGE
FROM DATASET_2


-- ANOTHER METHOD
--------------------------
SELECT order_number, order_status
FROM DATASET_2
GROUP BY order_number,order_status

--------------------------
SELECT COUNT(order_status)  AS CANCELLED_ORDERS
FROM (
		SELECT order_number, order_status
		FROM DATASET_2
		GROUP BY order_number,order_status) AS A
		WHERE order_status = 'CANCELLED'

----------------------------
SELECT COUNT(order_status) AS TOTAL_COUNT
FROM (
		SELECT order_number, order_status
		FROM DATASET_2
		GROUP BY order_number,order_status) AS B

-- FINALLY ------------------------------------------
SELECT (CANCELLED * 100.0/TOTAL) AS CANCELLED_PERCENT
FROM (
		SELECT 
		(SELECT COUNT(order_status)
		FROM (
				SELECT order_number, order_status
				FROM DATASET_2
				GROUP BY order_number,order_status) as A
				WHERE order_status = 'CANCELLED') AS CANCELLED,
   
				(
				SELECT COUNT(order_status) AS TOTAL_COUNT
				FROM(
						SELECT order_number, order_status
						FROM DATASET_2
						GROUP BY order_number,order_status) AS B) AS TOTAL
    ) as C


-- What is the total sales generated by the store channel??
-----------------------------
SELECT store_channel, ((amount_per_unit * ordered_quantity) - ( item_discount )) AS REVENUE_ON_ITEMS
FROM DATASET_2

----------------------------
SELECT store_channel, ROUND(SUM(revenue_on_items),2) AS REVENUE
FROM (
		SELECT store_channel, ((amount_per_unit * ordered_quantity) - ( item_discount )) AS REVENUE_ON_ITEMS
		FROM DATASET_2) as A
		GROUP BY store_channel
		ORDER BY REVENUE DESC


--  Most sold items by company
SELECT distinct_item, ROUND(SUM(revenue_on_items),2) AS REVENUE
FROM (
		SELECT distinct_item, ((amount_per_unit * ordered_quantity) - ( item_discount )) AS REVENUE_ON_ITEMS
		FROM DATASET_2) as b
		GROUP BY distinct_item
		ORDER BY REVENUE DESC-------------------------------------------------------------------------------- Visualize the monthly trend of sales and orders.SELECT * FROM DATASET_2SELECT order_date, ROUND(SUM(ITEM_SALES),0) as DAILY_SALES, COUNT(DISTINCT order_number) AS ORDERS
FROM (
		SELECT order_date ,order_number, (ordered_quantity * amount_per_unit) - item_discount AS ITEM_SALES
		FROM DATASET_2) as A
		GROUP BY order_date
---------------------------------------------------------------------------------
--more queries for further analysis
select * from dataset_1

select * from dataset_2
Select count(distinct store_id) from dataset_1
where first_order_date is not Null

SELECT 
    COUNT(DISTINCT CASE WHEN COUNT(order_number) >= 30 THEN store_id END) AS stores_30_plus_orders,
    COUNT(DISTINCT store_id) AS total_stores
FROM dataset_2
GROUP BY store_id;

WITH store_order_counts AS (
    SELECT 
        store_id,
        COUNT(distinct order_number) AS order_count
    FROM dataset_2
    GROUP BY store_id
)

SELECT 
    COUNT(CASE WHEN order_count >= 30 THEN 1 END) AS stores_30_plus_orders,
    COUNT(*) AS total_stores
FROM store_order_counts;


----------


-- How many users signed up through paid channels?
SELECT acquisition_platform, COUNT(DISTINCT(store_id)) as NO_OF_USERS
FROM DATASET_1
WHERE acquisition_platform != 'Organic' and first_order_date is not null
GROUP BY acquisition_platform
ORDER BY NO_OF_USERS DESC






